/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Clases.ArchivoProducto;
import Clases.Informacion;
import Clases.Producto;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Usuario
 */
public class MantenimientoProducto extends javax.swing.JInternalFrame {
       private String[][] data = {};
    private DefaultTableModel modelo;
    private String[] cabecera = {"CODIGO", "TIPO", "FOTO", "MARCA", "MODELO", "PRECIO","DESCRIPCION","TAMAÑO"};
    protected ArchivoProducto p;
    /**
     * Creates new form MantenimientoProducto
     */
    public MantenimientoProducto() {
        initComponents();
        setSize(1000, 600);
        p=new ArchivoProducto("producto.txt");
        modelo = new DefaultTableModel(data, cabecera);
        tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnBusca1 = new javax.swing.JButton();
        btnElimina1 = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTamaño = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtFoto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblImagen = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("                    MANTENIMIENTO PRODUCTO");

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarProd20x20.png"))); // NOI18N
        btnBusca1.setText("Busca");
        btnBusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusca1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnBusca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 91, 47));

        btnElimina1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete16x16.png"))); // NOI18N
        btnElimina1.setText("Elimina");
        btnElimina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimina1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnElimina1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 91, 48));

        btnModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modify16x16.png"))); // NOI18N
        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel4.add(btnModifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 50));

        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/List16x16.png"))); // NOI18N
        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel4.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 91, 50));

        btnLimpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escobita.png"))); // NOI18N
        btnLimpia.setText("Limpia");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });
        jPanel4.add(btnLimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 91, 50));

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, -1));

        jLabel4.setText("Tamaño :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 17, -1, -1));

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tipo", "Celular", "Tablet", "Laptop" }));
        jPanel3.add(cboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 11, 106, 28));

        jLabel2.setText("Precio :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel5.setText("Modelo :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 49, -1, -1));

        jLabel3.setText("Marca :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        jLabel6.setText("Imagen  :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 78, -1, -1));

        jLabel7.setText("Descripcion :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 54, -1, -1));
        jPanel3.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, -1));
        jPanel3.add(txtTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, -1));
        jPanel3.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 110, -1));
        jPanel3.add(txtFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 110, -1));
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 190, -1));
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 110, -1));
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 110, -1));

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        lblImagen.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(lblImagen, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        int c = p.busca(leeCodigo());
        if (c == -1) {
            mensaje("Producto no encontrado");
        } else {
            Producto nuevo = new Producto(leeCodigo(), leetipo(), leefoto(), new Informacion(leeMarca(), leeModelo(),leePrecio(), leeDescripcion(), leeTamaño()));
            p.actualiza(nuevo, c);
            p.graba();
            mensaje("se ah modificado a : " + leeCodigo()+ " Exitosamente");

        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        mostrarLista();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        // TODO add your handling code here:
        txtCodigo.setText("");
        cboTipo.setSelectedIndex(0);
        txtMarca.setText("");
        txtPrecio.setText("");
        txtDescripcion.setText("");
        //txtSalida.setText("");
        txtCodigo.requestFocus();
        txtFoto.setText("");
        txtModelo.setText("");
        txtTamaño.setText("");
        lblImagen.setIcon(null);
        iniciaTabla();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void btnElimina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimina1ActionPerformed
   int c = p.busca(leeCodigo());
        if (c == -1) {
            mensaje( "Producto no encontrado");
        } else {
            p.elimina(c);
            p.graba();
            mensaje(leeCodigo()+ " Se ah Eliminado");
        }
    }//GEN-LAST:event_btnElimina1ActionPerformed

    private void btnBusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusca1ActionPerformed
         int c = p.busca(leeCodigo());
        if (c == -1) {
            mensaje("Producto no encontrado");
        } else {
            Producto n = p.getproducto(c);
            //txtSalida.setText("");
            lista(n);
        }
    }//GEN-LAST:event_btnBusca1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca1;
    private javax.swing.JButton btnElimina1;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtFoto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTamaño;
    // End of variables declaration//GEN-END:variables
     
private String leeCodigo() {
       return txtCodigo.getText();
    }
    private String leetipo() {
       return (String) cboTipo.getSelectedItem();
    }
    private String leefoto() {
       return txtFoto.getText();
    }
    private String leeMarca(){
        return txtMarca.getText();
    }
    private String leeModelo(){
        return txtModelo.getText();
    }
    private double leePrecio(){
        return Double.parseDouble(txtPrecio.getText());
    }
    private String leeDescripcion(){
        return txtDescripcion.getText();
    }
    private String leeTamaño(){
        return txtTamaño.getText();
   }
    public void lista(Producto c) {
        cboTipo.setSelectedItem("" + c.getTipo());
        txtMarca.setText("" + c.getInfo().getMarca());
        txtModelo.setText("" + c.getInfo().getModelo());
        txtPrecio.setText("" + c.getInfo().getPrecio());
        txtDescripcion.setText("" + c.getInfo().getDescripcion());
        txtTamaño.setText("" + c.getInfo().getTamaño());
        txtFoto.setText("" + c.getFoto());
        lblImagen.setIcon(new ImageIcon(getClass().getResource("/Imagenes/"+leefoto()+".png")));
        lblImagen.setText("");
    }
    
    private void imprime(String s) {
       //txtSalida.append(s+"\n");
    }
    private void mensaje(String s) {
        JOptionPane.showMessageDialog(this, s);
        
    }
    public void mostrarLista() {
        iniciaTabla();
        for (int i = 0; i < p.getN(); i++) {
            Producto n = p.getproducto(i);
            Object[] datos = {n.getCodigo(),n.getTipo(),n.getFoto(),
                              n.getInfo().getMarca(),n.getInfo().getModelo(),
                              n.getInfo().getPrecio(),n.getInfo().getDescripcion(),n.getInfo().getTamaño()};
            modelo.addRow(datos);
        }
    }
    public void iniciaTabla() {
        int filas = tabla.getRowCount();
        for (int fila = 0; fila < filas; fila++) {
            modelo.removeRow(0);


        }

        }


}
