/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Clases.ArchivoUsuario;
import Clases.Usuario;
import Principal.Registrar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class MantenimientoUsuario extends javax.swing.JInternalFrame {
    private String[][] data = {};
    private DefaultTableModel modelo;
    private String[] cabecera = {"DNI", "NOMBRE", "APELLIDO", "USUARIO", "CONTRASEÑA"};
    protected ArchivoUsuario af;
      public MantenimientoUsuario() {
        initComponents();
        setSize(1000, 600);
        af = new ArchivoUsuario("Usuario.txt");
        modelo = new DefaultTableModel(data, cabecera);
        tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBusca = new javax.swing.JButton();
        btnModifica = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnLimpia = new javax.swing.JButton();
        btnElimina = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANTENIMIENTO USUARIO ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personal48x48.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarProd20x20.png"))); // NOI18N
        btnBusca.setText("Busca");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBusca);

        btnModifica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modify16x16.png"))); // NOI18N
        btnModifica.setText("Modifica");
        btnModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificaActionPerformed(evt);
            }
        });
        jPanel3.add(btnModifica);

        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/List16x16.png"))); // NOI18N
        btnLista.setText("Lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel3.add(btnLista);

        btnLimpia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escobita.png"))); // NOI18N
        btnLimpia.setText("Limpia");
        btnLimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiaActionPerformed(evt);
            }
        });
        jPanel3.add(btnLimpia);

        btnElimina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Delete16x16.png"))); // NOI18N
        btnElimina.setText("Elimina");
        btnElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaActionPerformed(evt);
            }
        });
        jPanel3.add(btnElimina);

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clipboard16x16.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegistrar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 16, -1, -1));

        jLabel4.setText("Dni:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 42, -1, -1));

        jLabel5.setText("Apellido :");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 16, -1, -1));

        jLabel6.setText("Usuario :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 42, -1, -1));

        jLabel7.setText("Contraseña :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 16, -1, -1));
        jPanel4.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 13, 150, -1));
        jPanel4.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 39, 150, -1));
        jPanel4.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 13, 155, -1));
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 39, 155, -1));
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 39, 172, -1));

        jPanel6.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        int p = af.busca(leeDni());
        if (p == -1) {
            mensaje("Usuario no encontrado");
        } else {
            Usuario n = af.getUsuario(p);
            //txtSalida.setText("");
            lista(n);
        }
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificaActionPerformed
        // TODO add your handling code here:
        int p = af.busca(leeDni());
        if (p == -1) {
            mensaje("Usuario no encontrado");
        } else {
            Usuario nuevo = new Usuario(leeNombre(), leeApellido(), leeDni(), leeUsuario(), leeContraseña());
            af.actualiza(nuevo, p);
            af.graba();
            mensaje("se ah modificado a : " + leeDni()+ " Exitosamente");

        }
    }//GEN-LAST:event_btnModificaActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        mostrarLista();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnLimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiaActionPerformed
        // TODO add your handling code here:
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContraseña.setText("");
        //txtSalida.setText("");
        txtDni.requestFocus();
        iniciaTabla();
    }//GEN-LAST:event_btnLimpiaActionPerformed

    private void btnEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaActionPerformed
        // TODO add your handling code here:
        int p = af.busca(leeDni());
        if (p == -1) {
            mensaje( "Usuario no encontrado");
        } else {
            af.elimina(p);
            af.graba();
            mensaje(leeDni()+ " Se ah Eliminado");
        }
    }//GEN-LAST:event_btnEliminaActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        Registrar n=new Registrar();
        n.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnElimina;
    private javax.swing.JButton btnLimpia;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModifica;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
 
    public String leeNombre(){
        return txtNombre.getText();
    }
    public String leeApellido(){
        return txtApellido.getText();
    }
    public String leeDni(){
        return txtDni.getText();
    }
    public String leeUsuario(){
        return txtUsuario.getText();
    }
    public String leeContraseña(){
        return txtContraseña.getText();
    }
    public void mensaje(String s){
        JOptionPane.showMessageDialog(this, s);
    }
    /*public void imprimir(String s) {
        txtSalida.append(s + "\n");
    }**/
    public void lista(Usuario c) {
        txtNombre.setText("" + c.getNombre());
        txtApellido.setText("" + c.getApellido());
        txtUsuario.setText("" + c.getUsuario());
        txtContraseña.setText("" + c.getContraseña());

    }
    
    public void mostrarLista() {
        iniciaTabla();
        for (int i = 0; i < af.getN(); i++) {
            Usuario n = af.getUsuario(i);
            String[] datos = {n.getDni(),n.getNombre(),n.getApellido(),n.getUsuario(),n.getContraseña()};
            modelo.addRow(datos);
        }
    }
    public void iniciaTabla() {
        int filas = tabla.getRowCount();
        for (int fila = 0; fila < filas; fila++) {
            modelo.removeRow(0);


        }
    }


}
